### ISSUE TITLE
Return value of PercyDOM.snapshot() is not supported by .NET client

### ISSUE THREAD

**Issue by LSViana** [percy/percy-selenium-dotnet#42]
(This issue was [originally created in percy/cli](https://github.com/percy/cli/issues/1142), but it was moved here [under request](https://github.com/percy/cli/issues/1142#issuecomment-1326284907).)

## The problem

The [.NET Percy library](https://www.nuget.org/packages/PercyIO.Selenium) doesn't know how to handle [the object returned by Percy CLI in version 1.15.0](https://github.com/percy/cli/commit/87e733ebb610ad43d89310776698069ebbea30e5#diff-9824ccc3183bab9098281b8ae310bcea8c81433684fc02806e735ed97c66fe3cR70-R78), which was just a plain string previously.

## Environment

- Node version:
- `@percy/cli` version: 1.15.0
- Version of Percy SDK you’re using: .NET PercyIO.Selenium 1.0.0
- If needed, a build or snapshot ID: N/A
- OS version: Windows 11 (22621.819)
- Type of shell command-line [interface]: Windows Terminal

## Details

The code to take snapshot fails with an exception that has the following message:

```
Unable to cast object of type  System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.
```

Because the .NET client declares a `string` variable to store the result returned by the `PercyDOM.serialize()` method, but in v1.15.0 it started returning an `object` instead.

## Debug logs

There are no logs from the CLI because the .NET client fails to process the result of `PercyDOM.serialize()`, therefore it never contacts the CLI to post a snapshot.

## Code to reproduce issue

Use [PercyIO.Selenium v1.0.0](https://www.nuget.org/packages/PercyIO.Selenium) with [@percy/cli@1.15.0](https://www.npmjs.com/package/@percy/cli/v/1.15.0) (the latest available of both tools) to check the issue happening.

## Extra

It is _possible_ that this issue affects SDKs of other languages too if they're also expecting a `string`.

It's not a problem to me that the Percy team introduced breaking changes but, when doing that, please publish updates to the SDKs to help customers fix the problems quickly.

**Comment by itsjwala** [comment]
@LSViana please give the latest version a try, the issue should be resolved.

**Comment by LSViana** [comment]
@itsjwala Sorry for the delay to answer. After I rolled back the versions last month and things were working again, I switched my focus to other business priorities.

I just updated the implementation on my side to use the [PercyIO.Selenium](https://www.nuget.org/packages/PercyIO.Selenium) v1.1.0 and [@percy/cli](https://www.npmjs.com/package/@percy/cli) v1.16.0 and the integration is working correctly now.

Thank you for the support! 🙋‍♂️
